local_search_settings:
  extract_entity_settings:
    index_name: 'description_index'
    top_k: 10
    query_nodes: 100
    dimensions: 1536
  extract_chunk_settings:
    threshold: 0.30
    top_k: 5
  extract_relationship_settings:
    top_k: 10

litellm:
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 10000
  dimension: 1536
  embedding_model: "gemini-embedding"