model_list:
  - model_name: gemini-embedding 
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: os.environ/GEMINI_API_KEY1
      rpm: 10
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY1
      rpm: 10

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY2
      rpm: 10
    
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY3
      rpm: 10

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY4
      rpm: 10
    
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY5
      rpm: 10

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY6
      rpm: 10
    
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY7
      rpm: 10

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY8
      rpm: 10

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY9
      rpm: 10

  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY10
      rpm: 10

  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GEMINI_API_KEY10
      rpm: 10

  - model_name: llama
    litellm_params:
      model: groq/meta-llama/llama-4-scout-17b-16e-instruct
      api_key: os.environ/LLAMA_API_KEY
      rpm: 20

  - model_name: gpt-oss-120b
    litellm_params:
      model: groq/openai/gpt-oss-120b
      api_key: os.environ/LLAMA_API_KEY
      rpm: 20

  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_WESTUS_API_BASE
      api_key: os.environ/AZURE_WESTUS_API_KEY
      api_version: os.environ/AZURE_WESTUS_API_VERSION

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: os.environ/AZURE_WESTUS_API_BASE
      api_key: os.environ/AZURE_WESTUS_API_KEY
      api_version: os.environ/AZURE_SUNAI_API_VERSION

  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/gpt-4o-mini
      api_base: os.environ/AZURE_SWEDEN_API_BASE
      api_key: os.environ/AZURE_SWEDEN_API_KEY
      api_version: os.environ/AZURE_SWEDEN_API_VERSION

  - model_name: claude-sonnet-4-20250514
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_access_key_id: os.environ/AWS_CLAUDE__ACCESS_KEY
      aws_secret_access_key: os.environ/AWS_CLAUDE__SECRET_ACCESS_KEY
      aws_region_name: os.environ/AWS_CLAUDE__REGION

general_settings:
  master_key: "abc123"

litellm_settings:
  drop_params: true