parser:
  upload_folder_path: app/files

litellm:
  model: "gemini-2.5-flash"
  temperature: 0.0
  top_p: 1.0
  n: 1
  frequency_penalty: 0.0
  max_completion_tokens: 10000
  dimension: 1024
  reasoning_effort: "medium"
  embedding_model: "qwen3-embedding:0.6b"

chunker:
  max_token_per_chunk: 1000
  min_token_per_chunk: 500

deduplicate:
  threshold: 0.9
